### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by PetrusVermaak** [mmguero/cleanvid#3]
I get this error when running the cmd:
File "C:\Program Files\Python38\lib\codecs.py", line 504, in read     newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

my cmd: cleanvid.py -s tls.srt -i tls.mp4 -o tlsc.mp4 -w swears.txt

I have Python 3.8 64bit installed.

**Comment by PetrusVermaak** [comment]
C:\Portable\cleanvid>cleanvid.py -s tls.srt -i tls.mp4 -o tlsc.mkv -w swears.txt
Traceback (most recent call last):
  File "C:\Portable\cleanvid\cleanvid.py", line 150, in <module>
    cleaner.CreateCleanSubAndMuteList(cleanSubsFileSpec=args.subsOut)
  File "C:\Portable\cleanvid\cleanvid.py", line 91, in CreateCleanSubAndMuteList
    subs = pysrt.open(self.inputSubsFileSpec)
  File "C:\Portable\cleanvid\pysrt\srtfile.py", line 153, in open
    new_file.read(source_file, error_handling=error_handling)
  File "C:\Portable\cleanvid\pysrt\srtfile.py", line 181, in read
    self.extend(self.stream(source_file, error_handling=error_handling))
  File "C:\Program Files\Python38\lib\collections\__init__.py", line 1130, in extend
    self.data.extend(other)
  File "C:\Portable\cleanvid\pysrt\srtfile.py", line 204, in stream
    for index, line in enumerate(chain(source_file, '\n')):
  File "C:\Program Files\Python38\lib\codecs.py", line 714, in __next__
    return next(self.reader)
  File "C:\Program Files\Python38\lib\codecs.py", line 645, in __next__
    line = self.readline()
  File "C:\Program Files\Python38\lib\codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "C:\Program Files\Python38\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

**Comment by mmguero** [comment]
Try that fix, I think that should take care of it.
