### ISSUE TITLE
Multiple Audio Tracks

### ISSUE THREAD

**Issue by Protoc0l** [mmguero/cleanvid#36]
Thank you in advance for the help.  If the mkv container has mutliple audio tracks (7.1, 5.1 and stereo), is there a way to edit/cleanvid each audio track keeping the format of each track including multitracks? Currently it seems to be keeping only one if multiple tracks are present and converting then to audio (aac).  Even if i split the audio tracks to different mkv containers and process them individually with cleanvid, they seem to all be audio (aac) after processing each split audio track. (PS thank you for making this script, it has revolutionized my video processing for our familiy!)

**Comment by mmguero** [comment]
Thanks for the suggestion! I'm not getting much time to update this project these days but I agree with the usefulness of this, and will take it under advisement.

**Comment by davidpeele** [comment]
@Protoc0l This may be the issue I am running into. I think cleaned is keeping only the surround channels and all dialog gets removed (all I hear is background audio in the cleaned video for some videos). Are there any audio parameters for ffmpeg that you found to work?

**Comment by davidpeele** [comment]
After doing testing on this, it seems an amazing option for 5.1 audio would be to mute only the center, and front channels leaving the rear channels complete as most if not all dialogue comes from the front and especially the center channel.
Otherwise, this is a great tool. That does pretty much what I was hoping for.
Thank you for your work on this!

**Comment by mmguero** [comment]
I'm releasing a v1.7.0 that should handle this by adding options for `--audio-stream-list` and `--audio-stream-index` index. For example:

* list the audio streams

```bash
$ cleanvid -i Princess.Mononoke.mkv --audio-stream-list
1: aac, 48000 Hz, stereo, jpn
2: aac, 48000 Hz, stereo, eng
```

* clean the selected audio stream

```bash
$ cleanvid -i Princess.Mononoke.mkv --audio-stream-index 2
```

* attempting to clean a multi-audio-stream file without selecting which one you want raises an exception:

```bash
$cleanvid -i Princess.Mononoke.mkv
Traceback (most recent call last):
  File "cleanvid", line 8, in <module>
    sys.exit(RunCleanvid())
             ^^^^^^^^^^^^^
  File "cleanvid.py", line 834, in RunCleanvid
    cleaner.MultiplexCleanVideo()
  File "cleanvid.py", line 565, in MultiplexCleanVideo
    raise ValueError(
ValueError: Multiple audio streams, specify audio stream index with --audio-stream-index
```

The other, non-selected audio streams *should* go straight into the output video file as-is, completely untouched. The selected audio stream should be the only audio stream that's affected by the filter.

I'm interested to hear everybody's experience with this.

**Comment by mmguero** [comment]
Note that my use case is more for multi-language files rather than different stereo encodings, but I think it should work the same way. If not let me know.

**Comment by MatthewGrantAU** [comment]
This works great for filtering a single stream in a file.  I am also trying to mute multiple streams in one file, but this doesn't work. eg. I have both 5.1 and 2.0 streams and tried adding --audio-stream-index 1 and --audio-stream-index 2 to the same script but it only filters one stream.     Would be great so the filter still works no matter what the family have set the surround mode to (5.1 or 2.0)
